Repository mF2C/Documentation, pull requests merged in 2019-04, with the labels that each got.

#13 LM and UM documentation updated
  documentation/developer_guide/testing.rst
  documentation/user_guide/api.rst
Labels: SERVICE ORCHESTRATION, demo

#9 Update SLA Management instructions
  documentation/developer_guide/installation.rst
Labels: SERVICE ORCHESTRATION, enhancement

#14 Updated the device and device-dynamic
  documentation/developer_guide/testing.rst
Labels: demo

#15 myLeaderID has been deleted
  documentation/developer_guide/testing.rst
Labels: demo
